### ISSUE TITLE
Backend - Manual Match Functionality

### ISSUE THREAD

**Issue by dli357** [TournamentBuzz/main#21]
## Story/Task Details
- [x] Allow organizers to add/edit/delete matches
- [x] Get a list of matches that are published (or complete list of matches if you're authenticated as the organizer)

## API Endpoints
| Endpoint | Description | Request Method | Expected Input | Expected Output |
|-----------|--------------|--------------------|------------------|--------------------|
| `/matches/create` | Checks credentials and, if valid, allows the user to create a match under the tournament | `POST` | `{location: <string>, score: <string>, matchTime: <dateTime>, matchName: <string>, teamA: <int>, teamB:<int>, tournament: <int>}` | `{tournamentId: <int>, matchId: <int>}` |
| `/matches/edit` | Checks credentials and, if valid, allows the user to edit a match under a tournament| `POST` | `{matchId: <int>, matchName: <string>, location: <string>, score: <string>, matchTime: <dateTime>, partyA: <id>, partyB:<id>}` | `{tournamentId: <int>, matchId: <int>}` |
| `/matches/delete` | Checks credentials and, if valid, allows the user to delete a match | `POST` | `{matchId: <int>}` Valid user and JWT | `{deleteStatus: success_or_failure}` |
| `/matches/publish` | Checks credentials and, if valid, allows the user to publish a match | `POST` | `{matchId: <int>, publish: <boolean>}` | `{publishStatus: success_or_failure}` |
| `/matches/id/<id>` | Checks credentials and, if valid, allows the user to retrieve a match (if published, or, if the user is not the creator) | `GET` | Valid JWT and valid user | `{match: <matchObject>}` NOTE does not return published |
| `/tournaments/id/<id>/matches/` | Checks credentials and, if valid, allows the user to get matches associated with the tournament (private or public depending on whether the user is an organizer) | `GET` | N/A | `{matches: <Array[matchObject]>}` |

## Match Object
```
{
  id: <int>,
  location: <string>,
  score: <string>,
  matchTime: <dateTime>,
  matchName: <string>,
  tournament: <int>,
  teamA: <TeamObject>,
  teamB: <TeamObject>,
  published: <boolean>
}
```

## Team Table
```
{
  teamId: <number>
  player: <string>,
}
```

The backend should be able to handle which match table to pull from depending on whether the tournament is a team tournament or not.

### User Story: As an organizer, I want to add matches to a tournament manually.
Scenario 1: An organizer wants to add a match to a tournament.
Given the organizer is on the tournament page;
When the add match button pressed and all details for the match are entered;
Then the match is added to the tournament.
### User Story: As an organizer, I want to delete a match manually.
Scenario 1: An organizer wants to delete a match from a tournament.
Given the organizer is on the tournament matches page;
When the delete match button is pressed for a match;
Then the match is removed from the tournament.
### User Story: As an organizer, I want to edit a match manually.
Scenario 1: An organizer wants to edit a match in a tournament.
Given the organizer is on the tournament matches page;
When the edit match button is pressed for a match;
Then an interface pops up allowing the organizer to edit matches.
### User Story: As an organizer, I want to publish a match manually.
Scenario 1: An organizer wants to publish a match for a tournament.
Given the organizer is on the tournament matches page;
When the publish  match button is pressed for a match;
Then the match now can be viewed by people other than the organizer.

**Comment by alex-stetson** [comment]
Why doesn't the create endpoint want tournamentId in the body but edit, delete, and publish do? Is there a reason for this?
