### ISSUE TITLE
Finalize Tournament Model

### ISSUE THREAD

**Issue by dli357** [TournamentBuzz/main#22]
Consider whether we need separate match tables to handle individual matches or team matches. (Or maybe we can have each user be their own team for individual tournaments?)

Additionally, change the matchName to a matchDetails field instead and, instead of the score column, provide columns for the scores of both parties.

Finally, need to add a published or unpublished detail so that organizers can save their matches if they want to and not have it be public.

## Wrapper functions that need to be added:
| Function | Description |
|-----------|--------------|
| getTournament | Gets the tournament by id |
| getMatch | Gets the match by tournament and match id |
| createTournament | Creates a tournament |
| updateTournament | Updates a tournament by id |
| deleteTournament | Deletes a tournament by id |
| matches Stuff | Same functions for all matches, except by both tournament and match id |
| searchTournament | Search a tournament by name (does MySQL have this functionality?) |

**Comment by Xvx1** [comment]
Tentatively thinking of adding loserFeedsTo and winnerFeedsTo fields to match, and/or possibly roundNumber - will wait until bracket system more formalized to continue and will proceed for now as-is
