### ISSUE TITLE
Backend - Tournament Browser

### ISSUE THREAD

**Issue by dli357** [TournamentBuzz/main#23]
## Story/Task Details
- [ ] On the home page, should display a list sorted by date of upcoming tournaments
- [ ] Allow the user to search for tournaments by name and creator
- [ ] Allow the user to filter tournaments (under search?)

## API Endpoints
| Endpoint | Description | Request Method | Expected Input | Expected Output |
|-----------|--------------|--------------------|------------------|--------------------|
| `/tournaments` | Checks credentials and, if valid, allows the user to see upcoming tournaments | `GET` | `N/A` | `{tournaments: Array<tournamentObject>}` |
| `/tournaments/search` | Checks credentials and, if valid, allows the user to search for tournaments by name and creator| `POST` | `{search: <string>}` | `{tournaments: Array<tournamentObject>}` |

## Tournament Object
```
{
id: <number>,
creator: <string>,
description: <string>,
teamEvent: <boolean>,
location: <string>,
scoringType: <enum('Points')>,
tournamentName: <string>, 
tournamentType: <enum('Single Elim', 'Double Elim', 'Round-robin')>,
entryCost: <int>,
maxParticipants: <int>,
startDate: <dateTime>,
endDate: <dateTime>
}
```

TODO: Need to come up with a filter object that will allow us to describe filtering for tournaments

**Comment by alex-stetson** [comment]
It might be necessary for us to know the unique id of the organizer as well.
