### ISSUE TITLE
[Backend] Participant Teams and Tournament Signup

### ISSUE THREAD

**Issue by dli357** [TournamentBuzz/main#39]
## Story/Task Details
- [ ] Teams can sign up for tournaments

## API Endpoints
| Endpoint | Description | Request Method | Expected Input | Expected Output |
|-----------|--------------|--------------------|------------------|--------------------|
| `/tournaments/id/<id>/teams/create` | Checks credentials and, if valid, allows the user to create a team for a tournament | `POST` | `{teamName: <string>}` valid JWT | `{teamId: <Id>}` |
| `/tournaments/id/<id>/teams/withdraw` | Checks credentials and, if valid, allows the user to see all teams in a tournament | `POST` | `{teamId: <id>}` | `{withdrawStatus: <bool>}` |
| `/tournaments/id/<id>/teams` | Checks credentials and, if valid, allows the user to withdraw a team from a tournament if they are the team captain | `GET` | `N/A` | `{teams: <Array[teamObjects]>}` |
| `/teams/invite` | Checks credentials and, if valid, allows the captain to invite a member to their team | `POST` | `{team_id: <id>, email: <string>}` | `{inviteStatus: <bool>}` |
| `/teams/remove` | Checks credentials and, if valid, allows the captain to kick a member from their team | `POST` | `{team_id: <id>, email: <string>}` | `{kickStatus: <bool>}` |
| `/teams/promote` | Checks credentials and, if valid, allows the captain of the team to promote another member to captain (replacing themselves) | `POST` | `{team_id: <id>, email_to_promote: <string>}` | `{promoteStatus: <bool>}` |
| `/teams/id/<id>/` | Checks credentials and, if valid, allows the user to get see a team | `GET` | `N/A` | `{team: <teamObject>}` |
| `/teams/id/<id>/members` | Checks credentials and, if valid, allows the user to get all members of a team | `GET` | `N/A` | `{members: <Array[teamMembersObject]>}` |

SQL Statements Needed:
GetUserTeams - Gets all the teams a user is on (not yet necessarily, but will be used in the future)
GetUserTeamFromTournament - Gets the team that the user is on in a tournament
InviteTeamMember - Invites a member to a team given an email and a teamId
RemoveTeamMember- Removes a team member from a team given an email and teamId
AcceptInvitation - Changes a team member's status to approved

NOTE: Declining an invitation will just remove the player from a team (equivalent to a kick).

## Acceptance Scenarios
- Given: A participant wants to sign up for a tournament
- When: The user clicks on the sign-up button (for single tournaments) or redirected to the team signup page (team tournament)
- Then: The team is created and added to the teams table and related to the tournament

## Done Done Criteria
Unit Tests are passing

**Comment by alex-stetson** [comment]
I have some questions on these endpoints. First, shouldn't the team id be auto generated by the backend during signup? Why would the frontend be passing it in? Shouldn't the frontend be passing in other things instead like team name and other team details?

**Comment by dli357** [comment]
I believe that the frontend passes in the team that the user will use to sign up for the tournament. This, of course, is assuming that teams have to be formed before the team can be signed up for a tournament. In that case, the user has to choose which team they want to sign up for the tournament with, hence passing in the team ID.

I believe that we were expecting to create teams as a separate entity from the tournaments, and then, after creating a team, you could sign the team up for whatever tournament you wanted.

**Comment by alex-stetson** [comment]
I thought we talked about this last meeting where we stated that teams will have to be associated with a tournament to avoid teams without tournaments (so a new team is created for each tournament signup)
Regardless of what way we go, there are still no endpoints defined to create the teams themselves.

**Comment by dli357** [comment]
Yeah I believe that we just wanted to have the framework in place for this sprint but not necessarily complete the teams API. Our primary focus should be matches.

And I can see some merit to what you have described, it makes more sense. I guess we could add a /tournament/id/<id>/teams/create_edit_delete to handle this as well. That would mean no teams with no tournaments.
