### ISSUE TITLE
[Backend] Add/Get/Remove Referees

### ISSUE THREAD

**Issue by dli357** [TournamentBuzz/main#62]
## Story/Task Details
- [x] Get a list of referees
- [x] Add referees to a tournament
- [x] Remove referees from a tournament

## API Endpoints
| Endpoint | Description | Request Method | Expected Input | Expected Output |
|-----------|--------------|--------------------|------------------|--------------------|
| `/tournaments/id/<id>/referees` | Returns a list of referees for the tournament | `GET` | None | `{referees: [<email>]}` |
| `/tournaments/id/<id>/referees/add` | Checks JWT, and, if valid, adds the referee to the tournament | `POST` | `{email: <email>}`| `{addSuccess: <boolean>}` |
| `/tournaments/id/<id>/referees/remove` | Checks JWT, and, if valid, removes the referee from the tournament | `POST` | `{email: <email>}` | `{removeSuccess: <boolean>` |

## Acceptance Scenarios
- Given: A tournament organizer wants to add a referee to a tournament
- When: The tournament organizer is on the referees page and submits an email of a person
- Then: The person (if valid) is added as a referee to the tournament (ensure person exists and not currently in the tournament).

- Given: A tournament organizer wants to remove a referee from a tournament
- When: The tournament organizer is on the referees page and removes an email of a person
- Then: The person is removed as a referee from the tournament.

## Done Done Criteria
Passing unit tests

**Comment by alex-stetson** [comment]
Shouldn't remove also expect email in the body?

**Comment by dli357** [comment]
Oops, fixed.
