### ISSUE TITLE
[Backend] Submit Match Score

### ISSUE THREAD

**Issue by dli357** [TournamentBuzz/main#64]
## Story/Task Details
- [x] Allow for referees to edit matches to submit scores

## API Endpoints
| Endpoint | Description | Request Method | Expected Input | Expected Output |
|-----------|--------------|--------------------|------------------|--------------------|
| `/matches/id/<id>/submit` | Checks credentials and, if valid and match is public, allows the user to scores for a match | `POST` | {scoreA: <int>, scoreB: <int>, winner: <player>} | `{scoreSubmitSuccess: <bool>}` |

## Acceptance Scenarios
- Given: A referee wants to submit a score
- When: The user is on a match page of a tournament of which they are a referee
- Then: The referee is shown a button that takes them to a score submission page

## Done Done Criteria
Passing unit tests

**Comment by alex-stetson** [comment]
Can you provide more details on the input? I'm assuming that score should just be a number but what about winner? Should that be a team ID?

**Comment by dli357** [comment]
Yes, the score can be whatever format (used for display purposes only) but the winner must be a team ID. Ideally, we would implement this using a dropdown format on the frontend.
