### ISSUE TITLE
Endpoint for getting user list for team invitations

### ISSUE THREAD

**Issue by alex-stetson** [TournamentBuzz/main#75]
## Story/Task Details
- Endpoint gets all users that are not the current user (team creator) and are not currently part of or invited to the team 
- Endpoint returns an array of user objects (containing emails and display names)

**Comment by dli357** [comment]
## API Endpoints
| Endpoint | Description | Request Method | Expected Input | Expected Output |
|-----------|--------------|--------------------|------------------|--------------------|
| `/user` | Returns a list of users (potential security issues, we'll work around it for now) | `GET` | `Valid JWT` | `{uesrs: [<userObject>]}` |

**Comment by dli357** [comment]
Implemented with commit 057aa393903921e7d2d03dc026af474d24fb681e

**Comment by alex-stetson** [comment]
While the current endpoint is a temporary workaround, we really need a better solution so that the current team members (and the leader) do no appear in the listing. 
Also, we need to get the user display names in addition to the emails so that the listing can display actual names rather than emails.
