### ISSUE TITLE
Various Backend Issues

### ISSUE THREAD

**Issue by alex-stetson** [TournamentBuzz/main#79]
## Story/Task Details
- Team deletion is broken
- Manual match creation is still broken
- Match deletion may be broken (can't be tested because match creation is broken)

**Comment by dli357** [comment]
Working on a fix!

**Comment by dli357** [comment]
Resolved via 969d0473f53682072cc215c1562fcc8b3b91ffea.

- Team deletion was a frontend issue
- I was unable to reproduce the match creation issue.
- I was able to confirm that match deletion is functional.
